name: Compliance Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  compliance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Test
        run: |
          ci/rpm7/build.sh -s compliance -tp $(pwd)