name: Publish Snapshot Image from master

on:
  push:
#    branches:
#      - master

jobs:
  deploy-release:

    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:

    - name: Get Latest Release
      id: latest_version
      uses: abatilo/release-info-action@v1.3.0
      with:
        owner: telefonicaid
        repo: fiware-orion

    - name: Echo version
      run: |
        echo "Version ${{ steps.latest_version.outputs.latest_tag }}"

    - name: Increment version
      id: increment-semver-minor
      env:
        LATEST_RELEASE: ${{ steps.latest_version.outputs.latest_tag }}
      run: |
        .github/incrementVersion.sh

    - name: Get the output version
      run: |
        echo "The new minor version was ${{ steps.increment-semver-minor.outputs.version }}"
