name: Publish Snapshot Image from master

on:
  push:
#    branches:
#      - master

jobs:
  deploy-release:

    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:
    - name: Get Latest Release
      id: latest_version
      uses: abatilo/release-info-action@v1.3.0
      with:
        owner: telefonica
        repo: fiware-orion

    - name: Echo version
      env: |
        LATEST: ${{ steps.latest_version.outputs.latest_tag }}
      run: |
        echo "Version $LATEST"
