name: Unit Tests

on:
  push:
  pull_request:
    branches:
      - master

env:
  TEST_IMAGE_NAME: fiware/orion-ci:rpm7

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run functional test
        run: |
          docker run -t --rm -v $(pwd):/opt/fiware-orion ${{ env.TEST_IMAGE_NAME }} build -midqts unit