name: Unit Tests

on:
  push:
  pull_request:
    branches:
      - master

env:
  TEST_IMAGE_NAME: fiware/orion-ci:rpm7

jobs:
  unit:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2

      - name: Run functional test
        run: |
          docker run  --network host -t --rm -v $(pwd):/opt/fiware-orion ${{ env.TEST_IMAGE_NAME }} build -miqts unit